#
version: "3.2"

networks:
  macvlan-net-vm-node1:
    external: true

services:
  bk1:
    image: aldrin/bookkeeper
    restart: "no"
    hostname: bk-c1-n1
    networks:
      macvlan-net-vm-node1:
        ipv4_address: 172.16.11.4
    environment:
      ZK_SERVERS: "zk-c1-n1:2181,zk-c1-n2:2181,zk-c1-n3:2181"
  bk2:
    image: aldrin/bookkeeper
    restart: "no"
    hostname: bk-c1-n2
    networks:
      macvlan-net-vm-node1:
        ipv4_address: 172.16.11.5
    environment:
      ZK_SERVERS: "zk-c1-n1:2181,zk-c1-n2:2181,zk-c1-n3:2181"
  bk3:
    image: aldrin/bookkeeper
    restart: "no"
    hostname: bk-c1-n3
    networks:
      macvlan-net-vm-node1:
        ipv4_address: 172.16.11.6
    environment:
      ZK_SERVERS: "zk-c1-n1:2181,zk-c1-n2:2181,zk-c1-n3:2181"

#::END::
